Revisão do layout e padronizacao
gruponasaDH/SpaceNBeyond pull request #23
Opened 2020-03-21 20:12 UTC by solfalcao

Revisão de Layout e padronização
Criação da activity recuperação de senha

2020-03-21 21:32 UTC, karoline-robles commented on app/src/main/java/com/example/spacenbeyond/Views/ImagensFragment.java
> +package com.example.spacenbeyond.Views;
Geralmente os nomes de pacotes começam com letras minúsculas, atualizar.

2020-03-21 21:44 UTC, karoline-robles commented on app/src/main/res/drawable/button_custom.xml
> +        android:drawable="@drawable/btnCustom"
A caixa alta não funciona em alguns pcs, favor colocar letra minúscula.

2020-03-21 21:47 UTC, karoline-robles commented on app/src/main/res/values/colors.xml
>      <color name="ColorButton">#C0CCDA</color>
Duplicação de cor.

2020-03-21 21:52 UTC, karoline-robles requested changes
Code-review, por favor verificar se builda.

2020-03-22 22:39 UTC, solfalcao commented on app/src/main/java/com/example/spacenbeyond/Views/ImagensFragment.java
> +package com.example.spacenbeyond.Views;
Corrigido subi a branch

2020-03-22 22:39 UTC, solfalcao commented on app/src/main/res/drawable/button_custom.xml
> +        android:drawable="@drawable/btnCustom"
Corrigido

2020-03-22 22:40 UTC, solfalcao commented on app/src/main/res/values/colors.xml
>      <color name="ColorButton">#C0CCDA</color>
corrigido

2020-03-22 22:41 UTC, solfalcao commented
O app está buildando normalmente, os packages foram alterados para cx baixa

2020-03-23 04:37 UTC, closed without merging